# Generated by Django 2.2.7 on 2019-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191223_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, default='what', to='feed.Article'),
        ),
    ]
