# Generated by Django 2.2.7 on 2020-03-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191223_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, to='feed.Article'),
        ),
    ]
