# Generated by Django 2.2.7 on 2020-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('url_to_image', models.URLField(null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
    ]
