# Generated by Django 2.2.7 on 2020-03-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='none', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
