# Generated by Django 2.2.7 on 2020-03-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200312_2052'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('category', 'title'), name='Unique article'),
        ),
    ]
