# Generated by Django 2.2.7 on 2020-03-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200312_2156'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='Unique article',
        ),
    ]
